
services:
  backend:
    build:
      context: ./analizer_backend
    ports:
      - "5000:5000"
    volumes:
      - ./analizer_backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./analizer_frontend

    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
